POST http://admin:root@localhost:5984/iiv_db/_find
Content-Type: application/json

{
    "selector":{
        "_id": {"$gt":null}
    },
    "fields": ["_id","_rev","nome","lat","long","zoom","regione","descrizione","foto"]
}

###

GET http://admin:root@localhost:5984/iiv_db/_all_docs
###

GET http://admin:root@localhost:5984/iiv_db/id_elemento

###
POST http://admin:root@localhost:5984/iiv_db/_find
Content-Type: application/json

{
    "selector":{
        "_id": {"$gt":null}
    },
    "fields": ["_id","_rev","nome","lat","long","zoom","stazione"]
}


###
PUT http://admin:root@localhost:5984/iiv_db