
PUT  http://admin:root@localhost:5984/iiv_db/b38071c6d307b952f69928b7e9000b3f
Content-Type: application/json

{
"_rev":"1-db2eacef4ce9bf98d0267475ddd5b5b0",
   "nome":"Castel Gandolfo",
        "regione":"Lazio",
        "lat":"41.7487496",
        "long":"12.6353254",
        "zoom":"14",
        "foto":["../media/borghi/castel-gandolfo-1.jpg","../media/borghi/castel-gandolfo-2.webp","../media/borghi/castel-gandolfo-3.jpg"],
        "descrizione":"Splendidamente affacciato sul Lago Albano, Castel Gandolfo è noto per la bellezza della natura che lo circonda e per l’eleganza del centro storico cinto da mura, che l’ha fatto eleggere uno dei Borghi più belli d’Italia. Conosciuto anche per essere la residenza estiva dei papi, qui si trova il Palazzo Pontificio."
    

}

###
GET https://www.booking.com/searchresults.it.html?ss=castel%20gandolfo&checkin_year=2022&checkin_month=10&checkin_monthday=1&checkout_year=2022&checkout_month=10&checkout_monthday=2&no_rooms=1&group_adults=1&group_children=0


###
Content-Type: application/json
 {
    "ss":"Castel Gandolfo",
    "checkin_year":"2022",
    "checkin_month":"06",
    "checkin_monthday":"5",
    "checkout_year":"2022",
    "checkout_month":"06",
    "checkout_monthday":"7",
    "no_rooms":"1",
    "group_adults":"1"
  }
