name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  API_MAPS: ${{ secrets.API_MAPS }}
  API_WHEATHER: ${{ secrets.API_WHEATHER }}
  CLIENT_ID_CALENDAR: ${{ secrets.CLIENT_ID_CALENDAR }}
  SECRET_ID_CALENDAR: ${{ secrets.SECRET_ID_CALENDAR }}
  RED_URI: ${{ secrets.RED_URI }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
